version: v1.0
ingress:
  # default block subdomains is disabled 
  #blockSubdomains:
  #  enabled: true # default: false
  ipv6:  true
  rules:
    - host: admin.localhost
      tls: 
        enabled: true   # default: false
        certificateEmail: letsencrypt@poseidon.com # required if tls is enabled
      http:
        paths:
          - path: /
            matching: prefix
            service:
              name: grafana
              port: application
          - path: /rick
            matching: exact
            service:
              name: rickroll
              port: application

    - host: app.localhost
      tls: 
        enabled: true   # default: false
        certificateEmail: letsencrypt@poseidon.com # required if tls is enabled
      http:
        paths:
          - path: /
            matching: prefix
            service:
              name: poseidon
              port: application # initial igored

    - host: localhost
      http:
        paths:
          - path: /
            matching: prefix
            service:
              name: frontend
          - path: /rick
            matching: exact
            service:
              name: rickroll
