# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check formatting with gofmt
      run: |
        unformatted=$(gofmt -l ./internal)
        if [ -n "$unformatted" ]; then
          echo "The following files are not properly formatted:"
          echo "$unformatted"
          exit 1
        fi
        unformatted=$(gofmt -l ./cmd)
        if [ -n "$unformatted" ]; then
          echo "The following files are not properly formatted:"
          echo "$unformatted"
          exit 1
        fi

  test:
    runs-on: ubuntu-latest
    needs: format  
    steps:
    - uses: actions/checkout@v4

    - name: Read Go version
      id: go-version
      run: echo "version=$(cat .go-version)" >> $GITHUB_OUTPUT

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ steps.go-version.outputs.version }}
      
    - name: Test
      run: go test -v ./...
